version: 2.1

jobs:
  test-build-release:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout
      - run:
          name: Git Config
          command: |
            git config --global user.email "himanshuallinone001@gmail.com" && \
            git config --global user.name "Himanshu Gupta"
      - run:
          name: Test
          command: mvn test
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Release
          command: mvn --batch-mode release:prepare release:perform -s .circleci/settings.xml
workflows:
  "Test-Build-Release":
    jobs:
      - test-build-release:
          filters:
            branches:
              only:
                - main