version: 2.1

jobs:
  test-build-release:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout
      - run:
          name: Creating Directory and File
          command: |
            sudo mkdir -p $LOG_PATH && \
            sudo touch $LOG_PATH/$LOG_FILE_NAME && \
            sudo chmod 777 $LOG_PATH/$LOG_FILE_NAME
      - run:
          name: Git Config
          command: |
            git config --global user.email $GIT_USER_EMAIL && \
            git config --global user.name $GIT_USER_NAME
      - run:
          name: Test
          command: mvn test
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Release
          command: mvn --batch-mode release:prepare release:perform -s .circleci/settings.xml
workflows:
  "Test-Build-Release":
    jobs:
      - test-build-release:
          context:
            - SECRETS
            - COMMONS
          filters:
            branches:
              only:
                - main